- hosts: localhost

  tasks:
    - git:
        repo: https://github.com/RodrigoAlmeidaPereira/devops-example.git
        dest: /home/ubuntu/devops

    - name: build docker image
      docker_image:
        name: web-server-devops-image
        path: /home/ubuntu/devops
        state: build
        force: yes

    - name: executing web-server devops example
      docker_container:
        name: web-server-devops-container 
        image: web-server-devops-image
        state: started
        ports:
          - "5000:5000"
